# Generated by Django 3.1.7 on 2021-10-05 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag1', models.CharField(max_length=15)),
                ('tag2', models.CharField(max_length=15)),
                ('tag3', models.CharField(max_length=15)),
                ('tag4', models.CharField(max_length=15)),
                ('tag5', models.CharField(max_length=15)),
                ('tag6', models.CharField(max_length=15)),
                ('tag7', models.CharField(max_length=15)),
                ('tag8', models.CharField(max_length=15)),
                ('tag9', models.CharField(max_length=15)),
                ('tag10', models.CharField(max_length=15)),
                ('threadid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply', models.CharField(max_length=1000)),
                ('threadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
