# Generated by Django 3.2.8 on 2021-10-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_dislike_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='threadid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='threadid',
            new_name='question',
        ),
    ]
