# Generated by Django 3.2.8 on 2021-10-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_save'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('threadid', 'user_name')},
        ),
    ]
