# Generated by Django 3.2.8 on 2021-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_save_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
