# Generated by Django 3.2.8 on 2021-10-24 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='question',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='user',
        ),
        migrations.AddField(
            model_name='notify',
            name='notify',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
