# Generated by Django 3.2.7 on 2021-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_newuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, default='pic.jpeg', null=True, upload_to=''),
        ),
    ]
