# Generated by Django 3.1.7 on 2021-10-15 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_newuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='fb_link',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='interest_form_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/in/'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
