# Generated by Django 3.2.8 on 2021-10-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211025_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='notify',
            new_name='message',
        ),
    ]
