# Generated by Django 3.1.7 on 2021-10-16 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20211015_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.question')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
