# Generated by Django 3.1.7 on 2021-10-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20211016_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
